#ifndef COLLECTIONS_GLOBAL_H
#define COLLECTIONS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COLLECTIONS_LIBRARY)
#  define COLLECTIONSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COLLECTIONSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COLLECTIONS_GLOBAL_H
