#ifndef LINKEDLISTSLIB_GLOBAL_H
#define LINKEDLISTSLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LINKEDLISTSLIB_LIBRARY)
#  define LINKEDLISTSLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LINKEDLISTSLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LINKEDLISTSLIB_GLOBAL_H
